services:
  crystal:
    build:
      context: ../crystal/
      dockerfile: Dockerfile.local
    environment:
      - CHLORIA_API_KEY=${CHLORIA_API_KEY}
      - CHLORIA_API_SECRET=${CHLORIA_API_SECRET}
      - CRYSTAL_LOG_LEVEL=info
    volumes:
      - ../:/usr/src/crystal/
    tty: true
    working_dir: /usr/src/crystal/crystal/
