services:
  crystal-ai:
    platform: linux/amd64
    build:
      context: ../crystal-ai/
      dockerfile: Dockerfile.local
    environment:
      - CRYSTAL_LOG_LEVEL=info
    volumes:
      - ../:/usr/local/src/crystal/
    tty: true
    working_dir: /usr/local/src/crystal/crystal-ai/
