[project]
name = "crystal-ai"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "nltk>=3.9.1",
    "openai>=1.68.2",
    "pykakasi>=2.3.0",
    "pylcs>=0.1.1",
    "requests>=2.32.3",
    "unsloth>=2025.3.19",
    "vllm>=0.8.2",
]
