FROM ghcr.io/ggml-org/llama.cpp:light-b4927

# Prerequisites
RUN apt update -y
RUN apt install -y git

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# Link the llama.cpp libraries
# Ref: https://github.com/ggml-org/llama.cpp/blob/b4927/.devops/cpu.Dockerfile
RUN cp /app/lib* /usr/local/lib && \
    ldconfig /usr/local/lib
